config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}
  resources :users
  resources :articles do
    resources :comments
  end

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :create, Comment
      can :read, [Article, Comment]
      can :manage, User, id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: {minimum: 5}

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
  validates :commenter, presence: true
  validates :article, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments

  # ROLES = %i[admin moderator author banned]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource
  def index
    @articles = Article.all.paginate(page: params[:page], per_page: 3)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.all.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: "The article has been successfully created"
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: "The article has been successfully updated."
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:user_id, :title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comment was created successfully.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { redirect_to @article, alert: 'Comment was not saved successfully.' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
    # redirect_to article_path (@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :commenter, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_comments.html.erb
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p>
              <%= sanitize comment.commenter.html_safe%>
              <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p>
            <%=sanitize comment.body.html_safe %></p>
        </div>

      <% if signed_in? && current_user.admin? %>
          <%= link_to 'Delete', article_comment_path(comment.article, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

    <% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.cktext_area :text, rows: 10%>
    <!-- <%= f.text_area :text %> -->
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<div class="basic-container-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>Edit article</h2>
    </div><!--end panel-heading-->
    <div class="panel-body">
      <%= render 'form' %>
    </div><!--end panel-body-->
    <div class="panel-footer">
      <%= link_to 'Back', articles_path %>
    </div><!--end panel-footer-->
  </div><!--end panel-default-->
</div>

app/views/articles/index.html.erb
<div class="basic-container-2">
  <% @articles.each do |article| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><%= sanitize article.title.html_safe, tags: %w(a), attributes: %w(href src) %></h3><br>
        <small><em><%= "#{time_ago_in_words(article.created_at)} ago" %></em></small>
      </div><!--end panel-heading-->
      <div class="panel-body">
        <p>
          <%= sanitize article.text.html_safe, tags: %w(a img table p tbody tr td th span strong ul li h1 h2 h3 br caption), attributes: %w(href src border style cellpadding em) %>
        </p>
      </div><!--end panel-body-->
      <div class="panel-footer">
        <%= link_to 'Show', article_path(article)%>
        <%if signed_in? && current_user.admin?%>
          | <%= link_to 'Edit', edit_article_path(article)%> |
          <%= link_to 'Delete', article_path(article),
                            method: :delete,
                            data: {confirm: 'Are you sure?'} %>
       <% end %>
      </div><!--end panel-footer-->
    </div><!--end panel-default-->
  <% end %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= will_paginate @articles %>
      <% if signed_in? && current_user.admin?%>
      <br>
      <%= link_to 'New Article', new_article_path %>
      <% end %>
    </div><!--end panel-body-->
  </div><!--end panel-default-->
</div><!--end basic-container-->

app/views/articles/new.html.erb
<div class="basic-container-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>New article</h2>
    </div><!--end panel-heading-->
    <div class="panel-body">
      <%= render 'form' %>
    </div><!--end panel-body-->
    <div class="panel-footer">
      <%= link_to 'Back', articles_path %>
    </div><!--end panel-footer-->
  </div><!--end panel-default-->
</div>

app/views/articles/show.html.erb
<div class="basic-container-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= sanitize @article.title.html_safe, tags: %w(a), attributes: %w(href src) %></h3><br>
      <small><em><%= "#{time_ago_in_words(@article.created_at)} ago" %></em></small>
    </div>
    <!--end panel-header-->
    <div class="panel-body">
      <p>
        <%= sanitize @article.text.html_safe, tags: %w(a img table tbody tr td th span strong p ul li h1 h2 h3 br caption), attributes: %w(href src border style cellpadding em) %>
      </p>
    </div><!--end panel-body-->
    <% if signed_in? && current_user.admin?%>
      <div class="panel-footer">
        <%= link_to 'Edit', edit_article_path(@article) %> |
        <%= link_to 'Delete', article_path(@article),
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %>
      </div><!--end footer-->
    <% end %>
  </div><!--end panel-default-->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Comments</h3>
    </div><!--end panel-heading-->
    <div class="panel-body">
      <%= render 'comments' %>
      <%= will_paginate @comments %>

      <% if signed_in? %>
        <h3>Add a Comment:</h3>
        <%= render 'comments/form' %>
      <% else %>
        <p>Sign in to comment</p>
      <% end %>

    </div><!--end panel-body-->
    <div class="panel-footer">
      <%= link_to 'Back', articles_path %>
    </div><!--end panel-footer-->
  </div><!--end panel-default-->
</div><!--end basic-container-2-->

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong><br>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong><br>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.article, comment],
              method: :delete,
              data: {confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control'%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Raleway|Rock+Salt" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>How's it Cookin'?</title>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <ul id="links">
        <li><%= link_to 'Home', root_path%></li>
        <li><%= link_to 'Recipes', articles_path%></li>
        <li>
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
          <% end %>
        </li>
      </ul>
      <ul class="float-right">
        <li>
          <% if user_signed_in? %>
            <p>Signed in as <%= current_user.email %></p>
          <% end %>
        </li>
      </ul>

    </nav><!--end nav-->
    <div class="container-own">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div><!--end container-own-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="basic-container">
  <div class="panel panel-default">
    <div class="panel-body">
      <h1>Editing User</h1>

      <%= render 'form', user: @user %>

      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', users_path %>
    </div><!--end panel-body-->
  </div><!--end panel-default-->
</div><!--end basic-container-->

app/views/users/index.html.erb
<div class="basic-container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Users</h1>
    </div><!-- end panel-heading-->
    <div class="panel-body">
      <p id="notice"><%= notice %></p>
      <table>
        <thead>
          <tr>
            <th>First name</th>
            <th> Last name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <% if user == current_user%>
                <td><%= link_to 'Show', user %></td>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New User', new_user_path %>
    </div><!--end panel-body-->
  </div><!--end panel-default-->
</div><!--end basic-container-->

app/views/users/new.html.erb
<div class="basic-container">
  <div class="panel panel-default">
    <div class="panel-body">
      <h1>New User</h1>

      <%= render 'form', user: @user %>

      <%= link_to 'Back', users_path %>
    </div><!--end panel-body-->
  </div><!--end panel-default-->
</div><!--end basic-container-->

app/views/users/show.html.erb
<div class="basic-container">
  <div class="panel panel-default">
    <div class="panel-body">
      <p id="notice"><%= notice %></p>
      <p>
        <strong>First name:</strong>
        <%= @user.first_name %><br>
        <strong>Last name:</strong>
        <%= @user.last_name %>
      </p>
      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Back', users_path %>
    </div><!--end panel-body-->
  </div><!--end panel-default-->
</div><!--end basic-container-->

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="z-0">
    <%= image_tag('cwv-front.png', alt: 'Chef dog', id: 'chef-dog')%>
  </div>
  <div class="z-1">
    <h1>How's It Cookin'?</h1>
  </div>
</div>

<div class="basic-container">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <h3>How's It Cookin'?</h3>
          <p>
            <i>How's It Cookin'?</i> Is a humorous online recipe archive. All the
            recipes on this blog are purely for fun and not too great either. They are
            webmasters' favourite though. Some of them might be even delicious.
          </p>
          <p>
            At the moment there isn't a search feature for the recipes but keyword system and
            a favourite system might be added later on.
          </p>
          <p>
            Browse through recipes from the navigation below and <i>enjoy</i>!
          </p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <h3>Hello blog, this is dog</h3>
          <p><i>How's It Cookin'?</i> is a Ruby on Rails blog application. It has been developed with the beginning help of
            Ruby on rails blog tutorial into a Cook Book app that implements authentication, authorization, advanced text editor
            and other features.
          </p>
          <p>
            Registered admin users that have signed in can create, update and delete articles and comments made by users.
            Registered users can comment articles.
          </p>
          <p>The layout has been completed with SASS using Bootstrap.</p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <h3>Info point</h3>
          <p>Have some Goofy recipe ideas or improvement ideas? <br>
          Contact webmaster:<br>
          admiralmoonkey [at] gmail.com</p>
        </div>
      </div><!--end row-->
    </div><!--end panel-body-->
  </div><!--end panel-->
</div><!--end welcome-->